{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.295",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.295.jar",
          "url": "qxsl-0.1.295.jar",
          "size": 329101,
          "sha512": "c570ca40cda792d41940a4deedeec39f7ead36ae3d7c3f25e9b8665a20d583433583b03c2f8d690ba5a4197a939e4ce9c69815ca05b862383dbcc70fd17d7abc",
          "sha256": "f135fc4972f07c66d749d4916b2a957a773b60bd50bc719d5ebdc38f327ecf36",
          "sha1": "fc998e3c0b8d134c1112dd7bfdac428ef2b1e5c4",
          "md5": "7b48bd4097f39639e1597f420cb1a899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.295.jar",
          "url": "qxsl-0.1.295.jar",
          "size": 329101,
          "sha512": "c570ca40cda792d41940a4deedeec39f7ead36ae3d7c3f25e9b8665a20d583433583b03c2f8d690ba5a4197a939e4ce9c69815ca05b862383dbcc70fd17d7abc",
          "sha256": "f135fc4972f07c66d749d4916b2a957a773b60bd50bc719d5ebdc38f327ecf36",
          "sha1": "fc998e3c0b8d134c1112dd7bfdac428ef2b1e5c4",
          "md5": "7b48bd4097f39639e1597f420cb1a899"
        }
      ]
    }
  ]
}
