{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.281",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.281.jar",
          "url": "qxsl-0.1.281.jar",
          "size": 327564,
          "sha512": "9196320538be5929eb2e9dde0862f89cbc006c6d13c76fb2b80648f06a72390f34fd4cc7dfa3a004fe0be84d70b0557fc7f9adf9bb46f16439bba3cb5dda1936",
          "sha256": "0e468b863e5b72a33ff592b22307ec3173b3dd59cd5a9d3713f870c25e3df6b5",
          "sha1": "ab707acb3780a79983a3a2febfada8d4368d2fc4",
          "md5": "924cd10fc3a35935d6e9ee2483cf70aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.281.jar",
          "url": "qxsl-0.1.281.jar",
          "size": 327564,
          "sha512": "9196320538be5929eb2e9dde0862f89cbc006c6d13c76fb2b80648f06a72390f34fd4cc7dfa3a004fe0be84d70b0557fc7f9adf9bb46f16439bba3cb5dda1936",
          "sha256": "0e468b863e5b72a33ff592b22307ec3173b3dd59cd5a9d3713f870c25e3df6b5",
          "sha1": "ab707acb3780a79983a3a2febfada8d4368d2fc4",
          "md5": "924cd10fc3a35935d6e9ee2483cf70aa"
        }
      ]
    }
  ]
}
