{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.281",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.281.jar",
          "url": "qxsl-0.1.281.jar",
          "size": 327564,
          "sha512": "cf13f3acd94c9c1dd6a92a97fe5f57c74e4c2262fa24beacddebbe91ec9a4b4268df0d0ad8b83b558429ecb301847bbd442adf32db707ede9ceda0583b01e836",
          "sha256": "b5a7084ac18055f60694dfe971cddee066f21576087d2ad0e5be0cd16cc0b208",
          "sha1": "51705b9436d14b74ff2a5e151ffc8a7405024229",
          "md5": "5fc3e4dc7e268abeab720c2691641604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.281.jar",
          "url": "qxsl-0.1.281.jar",
          "size": 327564,
          "sha512": "cf13f3acd94c9c1dd6a92a97fe5f57c74e4c2262fa24beacddebbe91ec9a4b4268df0d0ad8b83b558429ecb301847bbd442adf32db707ede9ceda0583b01e836",
          "sha256": "b5a7084ac18055f60694dfe971cddee066f21576087d2ad0e5be0cd16cc0b208",
          "sha1": "51705b9436d14b74ff2a5e151ffc8a7405024229",
          "md5": "5fc3e4dc7e268abeab720c2691641604"
        }
      ]
    }
  ]
}
