{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.281",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.281.jar",
          "url": "qxsl-0.1.281.jar",
          "size": 327564,
          "sha512": "4ea9a23d51a76f9fcfc696b573a8db28dd3e0002561c8e6c466f8149552949f22351c3b95e1005ede80ee418098bb818df5e4062d81874fc779deb5de5025eed",
          "sha256": "967d62092775514ba1979bed3a98d50a445bb4c9b37fdf7484421f5e603ff14e",
          "sha1": "15ff889a6a66bf512e2430c161a7d7531ffbb9da",
          "md5": "967b26245e2e44f88b852b8c41c61a30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.281.jar",
          "url": "qxsl-0.1.281.jar",
          "size": 327564,
          "sha512": "4ea9a23d51a76f9fcfc696b573a8db28dd3e0002561c8e6c466f8149552949f22351c3b95e1005ede80ee418098bb818df5e4062d81874fc779deb5de5025eed",
          "sha256": "967d62092775514ba1979bed3a98d50a445bb4c9b37fdf7484421f5e603ff14e",
          "sha1": "15ff889a6a66bf512e2430c161a7d7531ffbb9da",
          "md5": "967b26245e2e44f88b852b8c41c61a30"
        }
      ]
    }
  ]
}
