{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.271",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.271.jar",
          "url": "qxsl-0.1.271.jar",
          "size": 326528,
          "sha512": "ee0ec381723a672df589224a3fb0b62f54ffc302456912741bd9c290cb5b754446a7f64121401cdc0ad3669554797c0f55bed70da9e1efd1150590e4420ba7a8",
          "sha256": "a1cd52e23d455cae7396dfa82ae83182ab8cffc06fce748462a92171cc933c82",
          "sha1": "a0e454a8d2ec62402961a5d40674670efa7c65b0",
          "md5": "0657f04c6e6a11753d9af93bf1aff041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.271.jar",
          "url": "qxsl-0.1.271.jar",
          "size": 326528,
          "sha512": "ee0ec381723a672df589224a3fb0b62f54ffc302456912741bd9c290cb5b754446a7f64121401cdc0ad3669554797c0f55bed70da9e1efd1150590e4420ba7a8",
          "sha256": "a1cd52e23d455cae7396dfa82ae83182ab8cffc06fce748462a92171cc933c82",
          "sha1": "a0e454a8d2ec62402961a5d40674670efa7c65b0",
          "md5": "0657f04c6e6a11753d9af93bf1aff041"
        }
      ]
    }
  ]
}
