{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.271",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.271.jar",
          "url": "qxsl-0.1.271.jar",
          "size": 326528,
          "sha512": "2a166e098f1624eb067bbe2312bb708580380b0baee6d8d7dde009839bc140739dd1b795d5a608a3b4849a69bfc08d75a8a680b0bfda72dff3eec53b4939bdfb",
          "sha256": "95ee7e01a46dd2084053804535b16f904cdb115fbe3f09f66cae133c73b289b1",
          "sha1": "d4d60948b5389cd4b56fa4b4d33b34d45009c010",
          "md5": "64d25425b5fa68ba7f6ad2e22ad22df6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.271.jar",
          "url": "qxsl-0.1.271.jar",
          "size": 326528,
          "sha512": "2a166e098f1624eb067bbe2312bb708580380b0baee6d8d7dde009839bc140739dd1b795d5a608a3b4849a69bfc08d75a8a680b0bfda72dff3eec53b4939bdfb",
          "sha256": "95ee7e01a46dd2084053804535b16f904cdb115fbe3f09f66cae133c73b289b1",
          "sha1": "d4d60948b5389cd4b56fa4b4d33b34d45009c010",
          "md5": "64d25425b5fa68ba7f6ad2e22ad22df6"
        }
      ]
    }
  ]
}
