{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.269",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.269.jar",
          "url": "qxsl-0.1.269.jar",
          "size": 326307,
          "sha512": "c7b0e6dcaf3b64a8a2128a44fc694e6fd72a967e7ad718770d9b2685c757f33ccafc13de971219c6048a7d04e77c57a6891d6e808be156aeff962552ca97299d",
          "sha256": "b431a6a8feb9475b6b99aecdb80b0690c1f92f282421d632d4c2699b6addff58",
          "sha1": "f20f9a21bf2f6b98e405071d92f138b1c73f39bc",
          "md5": "1ec3922b257e3b1ec6e94a1d2b2a8aaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.269.jar",
          "url": "qxsl-0.1.269.jar",
          "size": 326307,
          "sha512": "c7b0e6dcaf3b64a8a2128a44fc694e6fd72a967e7ad718770d9b2685c757f33ccafc13de971219c6048a7d04e77c57a6891d6e808be156aeff962552ca97299d",
          "sha256": "b431a6a8feb9475b6b99aecdb80b0690c1f92f282421d632d4c2699b6addff58",
          "sha1": "f20f9a21bf2f6b98e405071d92f138b1c73f39bc",
          "md5": "1ec3922b257e3b1ec6e94a1d2b2a8aaf"
        }
      ]
    }
  ]
}
