{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.269",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.269.jar",
          "url": "qxsl-0.1.269.jar",
          "size": 326307,
          "sha512": "b2309f696576ca67354abe36dd775989a08fa238ee9b74437434a8b069304152496fe0594b67e9396c9f2969b755810f8b27414c3c5b46c5efafa12582d57dac",
          "sha256": "47ed0a9f089ffb5b274035f61d793ec045f65a996130796e72c572d032710922",
          "sha1": "2e2e9805c813d5f467d023168610b9c254227fa2",
          "md5": "93ce36e39b4aac33783c7b7ec9422de0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.269.jar",
          "url": "qxsl-0.1.269.jar",
          "size": 326307,
          "sha512": "b2309f696576ca67354abe36dd775989a08fa238ee9b74437434a8b069304152496fe0594b67e9396c9f2969b755810f8b27414c3c5b46c5efafa12582d57dac",
          "sha256": "47ed0a9f089ffb5b274035f61d793ec045f65a996130796e72c572d032710922",
          "sha1": "2e2e9805c813d5f467d023168610b9c254227fa2",
          "md5": "93ce36e39b4aac33783c7b7ec9422de0"
        }
      ]
    }
  ]
}
