{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.269",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.269.jar",
          "url": "qxsl-0.1.269.jar",
          "size": 326307,
          "sha512": "3713f03cb0917409672fe83e60072709e0b4e3ad012418832979904d28d100642f1990e3839683e212f0360a59323b60bfc363590f62b8d7906a3b1b76a06818",
          "sha256": "6cbab6a8b67fc25426dd0ff2234326107b6adc15e117775a064bf7f5818f4c23",
          "sha1": "f18ca77a4bf36c4ec7b4263f0aa2370b6e29310f",
          "md5": "7952247c87551dc85d04462a48fca638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.269.jar",
          "url": "qxsl-0.1.269.jar",
          "size": 326307,
          "sha512": "3713f03cb0917409672fe83e60072709e0b4e3ad012418832979904d28d100642f1990e3839683e212f0360a59323b60bfc363590f62b8d7906a3b1b76a06818",
          "sha256": "6cbab6a8b67fc25426dd0ff2234326107b6adc15e117775a064bf7f5818f4c23",
          "sha1": "f18ca77a4bf36c4ec7b4263f0aa2370b6e29310f",
          "md5": "7952247c87551dc85d04462a48fca638"
        }
      ]
    }
  ]
}
