{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.285",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.285.jar",
          "url": "qxsl-0.1.285.jar",
          "size": 327658,
          "sha512": "76fde283987e873bbe2086af2ca2d313911cd65fafd198fd2a31c1864aa6a5607583239db495c1300a931b46015b93720350ea8da34fd01ccde7600c9e2c86bd",
          "sha256": "6b7734a73cb1ffe95bbda7bb91aa1d6478ca3837f389a29f810202e480f9c412",
          "sha1": "a717871bdb42693b5ca65f7a00a6e07fd3c0515d",
          "md5": "f7c23e8edec45a94021aaee038d9c27e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.285.jar",
          "url": "qxsl-0.1.285.jar",
          "size": 327658,
          "sha512": "76fde283987e873bbe2086af2ca2d313911cd65fafd198fd2a31c1864aa6a5607583239db495c1300a931b46015b93720350ea8da34fd01ccde7600c9e2c86bd",
          "sha256": "6b7734a73cb1ffe95bbda7bb91aa1d6478ca3837f389a29f810202e480f9c412",
          "sha1": "a717871bdb42693b5ca65f7a00a6e07fd3c0515d",
          "md5": "f7c23e8edec45a94021aaee038d9c27e"
        }
      ]
    }
  ]
}
