{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.285",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.285.jar",
          "url": "qxsl-0.1.285.jar",
          "size": 327658,
          "sha512": "7d6efa77299b58fec70c265a769cea91acfa8d82539798074e67263cf7852abb077a21b12063a5eaba3800c419f50da059ced68a42d1f90e73d7e7afa144427e",
          "sha256": "64bb4f4f9193dd6c707b0d5ed29c86001c474554af08e5513adae66631a9bf8b",
          "sha1": "dc288d0ed452828f76616483a32acd589ffabb03",
          "md5": "76db5991d96a43d0c2e9be0cda03f7db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.285.jar",
          "url": "qxsl-0.1.285.jar",
          "size": 327658,
          "sha512": "7d6efa77299b58fec70c265a769cea91acfa8d82539798074e67263cf7852abb077a21b12063a5eaba3800c419f50da059ced68a42d1f90e73d7e7afa144427e",
          "sha256": "64bb4f4f9193dd6c707b0d5ed29c86001c474554af08e5513adae66631a9bf8b",
          "sha1": "dc288d0ed452828f76616483a32acd589ffabb03",
          "md5": "76db5991d96a43d0c2e9be0cda03f7db"
        }
      ]
    }
  ]
}
