{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.287",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.287.jar",
          "url": "qxsl-0.1.287.jar",
          "size": 325178,
          "sha512": "1af3f9c5e5a40e4800b57ecb521fd7d7b118ac01d5be154cd9ef7b939c085c643940e689ca5b919e4bc6011096158cb27b020821729c4f5612c7fcb0ddbe3958",
          "sha256": "92036984317b35f9a631f62e9569d765918b8f9e30a8df6ecb95cbd6996480b8",
          "sha1": "9d173c4892734ffdc9c583f2e2a0b01d860b0f5f",
          "md5": "47d549ef3849da9439e83b9ad5b88913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.287.jar",
          "url": "qxsl-0.1.287.jar",
          "size": 325178,
          "sha512": "1af3f9c5e5a40e4800b57ecb521fd7d7b118ac01d5be154cd9ef7b939c085c643940e689ca5b919e4bc6011096158cb27b020821729c4f5612c7fcb0ddbe3958",
          "sha256": "92036984317b35f9a631f62e9569d765918b8f9e30a8df6ecb95cbd6996480b8",
          "sha1": "9d173c4892734ffdc9c583f2e2a0b01d860b0f5f",
          "md5": "47d549ef3849da9439e83b9ad5b88913"
        }
      ]
    }
  ]
}
