{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.293",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.293.jar",
          "url": "qxsl-0.1.293.jar",
          "size": 328617,
          "sha512": "b926ad366c2481e59dd8769ae84413d939035e147d419df6491bd4f450c055dd214e7ba4d5e63b2b587a60d6e93c5b22bc982c29e9d40a74c2f19a9a82b8b604",
          "sha256": "d482431086ae506c836621ba248434e7c1ef079211acf259e85b1b46299b7ed0",
          "sha1": "2531cbca5e508c3917e685c0314cd1e7cd1c0aa5",
          "md5": "95254090873c3a1a890617cb731ffb12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.293.jar",
          "url": "qxsl-0.1.293.jar",
          "size": 328617,
          "sha512": "b926ad366c2481e59dd8769ae84413d939035e147d419df6491bd4f450c055dd214e7ba4d5e63b2b587a60d6e93c5b22bc982c29e9d40a74c2f19a9a82b8b604",
          "sha256": "d482431086ae506c836621ba248434e7c1ef079211acf259e85b1b46299b7ed0",
          "sha1": "2531cbca5e508c3917e685c0314cd1e7cd1c0aa5",
          "md5": "95254090873c3a1a890617cb731ffb12"
        }
      ]
    }
  ]
}
