{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.293",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.293.jar",
          "url": "qxsl-0.1.293.jar",
          "size": 328618,
          "sha512": "6ac56249425c4d161b0396686162d1bbc7f1910d0848de776de1b2608a420f5a8d6710c78a568d1eee519e9baec56a5b2922b170821027fe518fcc41df06a3ab",
          "sha256": "6cc9501f5a0e63459998f071b5f0700324778487a92c911b0d9cca9ec357c7a9",
          "sha1": "ed535ec4c8b69e8164a1ed6877a02f3df0172726",
          "md5": "020f84c46a41f6adf41f4f511745990b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.293.jar",
          "url": "qxsl-0.1.293.jar",
          "size": 328618,
          "sha512": "6ac56249425c4d161b0396686162d1bbc7f1910d0848de776de1b2608a420f5a8d6710c78a568d1eee519e9baec56a5b2922b170821027fe518fcc41df06a3ab",
          "sha256": "6cc9501f5a0e63459998f071b5f0700324778487a92c911b0d9cca9ec357c7a9",
          "sha1": "ed535ec4c8b69e8164a1ed6877a02f3df0172726",
          "md5": "020f84c46a41f6adf41f4f511745990b"
        }
      ]
    }
  ]
}
