{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.293",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.293.jar",
          "url": "qxsl-0.1.293.jar",
          "size": 328605,
          "sha512": "97b08f44ea42e1931755b89127dc448a582cda34033c18f79e43bccbaadcda2b352b2a325864374f0785c3699e6147b28046e58e805d854679cc94a31dc20358",
          "sha256": "7e3a81651a9cd24a5c484a7caf4b4eb938c89466154601cdaeac395a3fa1c6fc",
          "sha1": "aeec7b41ff51ef5a074b448469a05efe45d4c565",
          "md5": "42f4b3235dae5adb59e3713e9aa507b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.293.jar",
          "url": "qxsl-0.1.293.jar",
          "size": 328605,
          "sha512": "97b08f44ea42e1931755b89127dc448a582cda34033c18f79e43bccbaadcda2b352b2a325864374f0785c3699e6147b28046e58e805d854679cc94a31dc20358",
          "sha256": "7e3a81651a9cd24a5c484a7caf4b4eb938c89466154601cdaeac395a3fa1c6fc",
          "sha1": "aeec7b41ff51ef5a074b448469a05efe45d4c565",
          "md5": "42f4b3235dae5adb59e3713e9aa507b0"
        }
      ]
    }
  ]
}
