{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.297",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.297.jar",
          "url": "qxsl-0.1.297.jar",
          "size": 331686,
          "sha512": "0b4b19a5ccf6c221c5416e264778475c157cf29c5b4896265314a5987f63d0d967f50205cd68e07228e099ac1a7e66afcfb1a37598e00aa7dc552221b09de09b",
          "sha256": "e2733cf25d9a0a974a030f547e28266fc448e91b8613f6e18cf9ce09074825c9",
          "sha1": "cf063cc7940375dd2190062f9a6ad19f508432b2",
          "md5": "3bb958b5f367df4c0e25d6d0f3eb56bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.297.jar",
          "url": "qxsl-0.1.297.jar",
          "size": 331686,
          "sha512": "0b4b19a5ccf6c221c5416e264778475c157cf29c5b4896265314a5987f63d0d967f50205cd68e07228e099ac1a7e66afcfb1a37598e00aa7dc552221b09de09b",
          "sha256": "e2733cf25d9a0a974a030f547e28266fc448e91b8613f6e18cf9ce09074825c9",
          "sha1": "cf063cc7940375dd2190062f9a6ad19f508432b2",
          "md5": "3bb958b5f367df4c0e25d6d0f3eb56bc"
        }
      ]
    }
  ]
}
