{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.297",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.297.jar",
          "url": "qxsl-0.1.297.jar",
          "size": 332431,
          "sha512": "0dfc7dd87941356199b79d39d0d4a1571244f7f75b750baa7baf83efe8de515699866e60abc6a5d662d878b60dd6e9a512c20d2b9eeb3013fc391906f400644e",
          "sha256": "bac588f49ae81aeca16f416282f71172360e0eba00f979e66dc55b9ad9af9c3b",
          "sha1": "e54b1066d7042e3ad03725afa1d4e2a314e75faf",
          "md5": "259c69d7f682cf991d4a38420ea8b6a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.297.jar",
          "url": "qxsl-0.1.297.jar",
          "size": 332431,
          "sha512": "0dfc7dd87941356199b79d39d0d4a1571244f7f75b750baa7baf83efe8de515699866e60abc6a5d662d878b60dd6e9a512c20d2b9eeb3013fc391906f400644e",
          "sha256": "bac588f49ae81aeca16f416282f71172360e0eba00f979e66dc55b9ad9af9c3b",
          "sha1": "e54b1066d7042e3ad03725afa1d4e2a314e75faf",
          "md5": "259c69d7f682cf991d4a38420ea8b6a7"
        }
      ]
    }
  ]
}
