{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.306",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.306.jar",
          "url": "qxsl-0.1.306.jar",
          "size": 336589,
          "sha512": "4978ba39a800fb61d2aeecff6d69d99194a14ef6005deb073c146391669feb1d4ec42a0b7e49bc47d1e5b8efaa76368537d22db9f6f2e6c727294a653db30df7",
          "sha256": "03d65e3f2909bb1751efa740b9900e375841f5077f76072738de9f0706a043ad",
          "sha1": "3ec98adf83a4aa19c80f3df6eee670d3b661327b",
          "md5": "5b19c0184b6f0aaee7b0fc53f4667cbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.306.jar",
          "url": "qxsl-0.1.306.jar",
          "size": 336589,
          "sha512": "4978ba39a800fb61d2aeecff6d69d99194a14ef6005deb073c146391669feb1d4ec42a0b7e49bc47d1e5b8efaa76368537d22db9f6f2e6c727294a653db30df7",
          "sha256": "03d65e3f2909bb1751efa740b9900e375841f5077f76072738de9f0706a043ad",
          "sha1": "3ec98adf83a4aa19c80f3df6eee670d3b661327b",
          "md5": "5b19c0184b6f0aaee7b0fc53f4667cbe"
        }
      ]
    }
  ]
}
