{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.278",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.278.jar",
          "url": "qxsl-0.1.278.jar",
          "size": 327150,
          "sha512": "fad6118c31b559b268f2404e786fc69e013e6e0f0b3ea2301ef8f318c7db2fc6b3b8bd07dce72bdc639c75e1f00d2e3e10d36bdf77d62ff49d80bc6caf894d78",
          "sha256": "57b8ea55bd4f7e01ec3ad5d24f2bd3fb9564b750367a29040cc3188e60fe798d",
          "sha1": "14eb74610e61bfbbf4516461d87ebc136f923ca3",
          "md5": "8636135d2aa2487a8f03f6a0707d88f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.278.jar",
          "url": "qxsl-0.1.278.jar",
          "size": 327150,
          "sha512": "fad6118c31b559b268f2404e786fc69e013e6e0f0b3ea2301ef8f318c7db2fc6b3b8bd07dce72bdc639c75e1f00d2e3e10d36bdf77d62ff49d80bc6caf894d78",
          "sha256": "57b8ea55bd4f7e01ec3ad5d24f2bd3fb9564b750367a29040cc3188e60fe798d",
          "sha1": "14eb74610e61bfbbf4516461d87ebc136f923ca3",
          "md5": "8636135d2aa2487a8f03f6a0707d88f4"
        }
      ]
    }
  ]
}
