{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.273",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.273.jar",
          "url": "qxsl-0.1.273.jar",
          "size": 326528,
          "sha512": "a56c102d41f247152045ab756cd93264c9b8f89769f9aced0d0fe295fa50b8b77cc83580c9871abd01eabe4190a6d29eb39dc229fb13ac2ed5e36ad3d4d72682",
          "sha256": "2a7841148e7524a46f66829df0403b08fa962de75ea6dbe55344df8f28abbba6",
          "sha1": "82c75dfdc9f94eac319051079aa3953b2464b85e",
          "md5": "b922c91c8a66c11f5cd863c6934ed0ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.273.jar",
          "url": "qxsl-0.1.273.jar",
          "size": 326528,
          "sha512": "a56c102d41f247152045ab756cd93264c9b8f89769f9aced0d0fe295fa50b8b77cc83580c9871abd01eabe4190a6d29eb39dc229fb13ac2ed5e36ad3d4d72682",
          "sha256": "2a7841148e7524a46f66829df0403b08fa962de75ea6dbe55344df8f28abbba6",
          "sha1": "82c75dfdc9f94eac319051079aa3953b2464b85e",
          "md5": "b922c91c8a66c11f5cd863c6934ed0ed"
        }
      ]
    }
  ]
}
