{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.299",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.299.jar",
          "url": "qxsl-0.1.299.jar",
          "size": 332570,
          "sha512": "5486da4561790267c9aaccdc3b5c084f53e23b97cfdc7b68befee984194a0418b72361dd59454577edf1564af4ccec8e9a6b5969c15e223cf5922ad3fd4276b0",
          "sha256": "2d085a7d14d52455436a3e4dd9458a41e093e422465da3c49e655d1a873f991c",
          "sha1": "5656636751c8534eca7cc634134eefa7d480f2a1",
          "md5": "e2e84b0d0bd66bbd7f19d1125f1a6382"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.299.jar",
          "url": "qxsl-0.1.299.jar",
          "size": 332570,
          "sha512": "5486da4561790267c9aaccdc3b5c084f53e23b97cfdc7b68befee984194a0418b72361dd59454577edf1564af4ccec8e9a6b5969c15e223cf5922ad3fd4276b0",
          "sha256": "2d085a7d14d52455436a3e4dd9458a41e093e422465da3c49e655d1a873f991c",
          "sha1": "5656636751c8534eca7cc634134eefa7d480f2a1",
          "md5": "e2e84b0d0bd66bbd7f19d1125f1a6382"
        }
      ]
    }
  ]
}
