{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.299",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.299.jar",
          "url": "qxsl-0.1.299.jar",
          "size": 332532,
          "sha512": "47b07593c51c909049519bd7df631a83b50ae48149ca312ebb88109ebfb1a9f167bd8d3915b6a17676dee36f7438e863a59acdc041cbae4601a3c49a0cc07fef",
          "sha256": "163041ce63b9f6a2ae656154257f3237db14f97b05a5699add7baa3a81ba2e62",
          "sha1": "e5df16fbc6cde9e9f91d97181ce6868904b2a2e7",
          "md5": "648bf45737e64cd37ca711bc04b9e205"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.299.jar",
          "url": "qxsl-0.1.299.jar",
          "size": 332532,
          "sha512": "47b07593c51c909049519bd7df631a83b50ae48149ca312ebb88109ebfb1a9f167bd8d3915b6a17676dee36f7438e863a59acdc041cbae4601a3c49a0cc07fef",
          "sha256": "163041ce63b9f6a2ae656154257f3237db14f97b05a5699add7baa3a81ba2e62",
          "sha1": "e5df16fbc6cde9e9f91d97181ce6868904b2a2e7",
          "md5": "648bf45737e64cd37ca711bc04b9e205"
        }
      ]
    }
  ]
}
