{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.288",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.288.jar",
          "url": "qxsl-0.1.288.jar",
          "size": 324913,
          "sha512": "507d23c5c4db839bd2697cc17fa5934a5f84ee5987dd81f3d5e82974974c980d0fcc550a3305dd1580f58cd84c0f3f9dd70f57e1a0368e307c209800e559aada",
          "sha256": "0fa3e6b6d6e2bd0fc0cfafde53fa2d12c73bb4d2c4537c9fabf57cc3efc6e65c",
          "sha1": "0d95e87c6101086dd32665e5599b883c5c420717",
          "md5": "b1eb69fe3cd62f8df74ec33df327e001"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.288.jar",
          "url": "qxsl-0.1.288.jar",
          "size": 324913,
          "sha512": "507d23c5c4db839bd2697cc17fa5934a5f84ee5987dd81f3d5e82974974c980d0fcc550a3305dd1580f58cd84c0f3f9dd70f57e1a0368e307c209800e559aada",
          "sha256": "0fa3e6b6d6e2bd0fc0cfafde53fa2d12c73bb4d2c4537c9fabf57cc3efc6e65c",
          "sha1": "0d95e87c6101086dd32665e5599b883c5c420717",
          "md5": "b1eb69fe3cd62f8df74ec33df327e001"
        }
      ]
    }
  ]
}
