{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.284",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.284.jar",
          "url": "qxsl-0.1.284.jar",
          "size": 327682,
          "sha512": "8f4252c54cffdf3d79334909f4ad176c00ab08616978024664baa8c4ec5c1615434d1dceb3e3cdb12fc298458cddbcd2bdf59fa0468a800a223d763c63dc92cd",
          "sha256": "6281f8d4b031fe849f35adc4669b04b35f36037453be053baa3ae27ebb5a4594",
          "sha1": "48e295cffc1282df5ced0a1f0f7f130bbdba9ecc",
          "md5": "87ba9aab3fb7c67090d47a12aec632b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.284.jar",
          "url": "qxsl-0.1.284.jar",
          "size": 327682,
          "sha512": "8f4252c54cffdf3d79334909f4ad176c00ab08616978024664baa8c4ec5c1615434d1dceb3e3cdb12fc298458cddbcd2bdf59fa0468a800a223d763c63dc92cd",
          "sha256": "6281f8d4b031fe849f35adc4669b04b35f36037453be053baa3ae27ebb5a4594",
          "sha1": "48e295cffc1282df5ced0a1f0f7f130bbdba9ecc",
          "md5": "87ba9aab3fb7c67090d47a12aec632b0"
        }
      ]
    }
  ]
}
