{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.284",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.284.jar",
          "url": "qxsl-0.1.284.jar",
          "size": 327682,
          "sha512": "047541a6acb8447c301464eb7228a12eb9aea5ef6b81d404304a501fc9d76b89cc41f723323cdd66fee28a57b44ea768a209fa4159667d7b426ac5f1b9da842c",
          "sha256": "6f4991ca86b23c1e5d3f513b0fa077c715a8fc757b409f372a29b83f46831e00",
          "sha1": "26bec851f4d8481af44c35f066e01ddfc9acf0f8",
          "md5": "b50eb5abe9768a5e31ba72fbfcbf8819"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.284.jar",
          "url": "qxsl-0.1.284.jar",
          "size": 327682,
          "sha512": "047541a6acb8447c301464eb7228a12eb9aea5ef6b81d404304a501fc9d76b89cc41f723323cdd66fee28a57b44ea768a209fa4159667d7b426ac5f1b9da842c",
          "sha256": "6f4991ca86b23c1e5d3f513b0fa077c715a8fc757b409f372a29b83f46831e00",
          "sha1": "26bec851f4d8481af44c35f066e01ddfc9acf0f8",
          "md5": "b50eb5abe9768a5e31ba72fbfcbf8819"
        }
      ]
    }
  ]
}
