{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.284",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.284.jar",
          "url": "qxsl-0.1.284.jar",
          "size": 327682,
          "sha512": "8eed1c5187a5fac648c95dafe4ab50d49a7dd1f38aca02ec3e81c2084a34997ea1b6f2a8f196b19835f6e0ac5509b74b8a5b533932190da00f64ede291da0495",
          "sha256": "e9450f9c8da5d968adecd0ec121610e9e321f4933d5c6c46ac32ae55f879455b",
          "sha1": "0c8ed0c35efc989e38b90c49562958b36ed1ed1c",
          "md5": "023162f3b7190513c97676ff41b53d17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.284.jar",
          "url": "qxsl-0.1.284.jar",
          "size": 327682,
          "sha512": "8eed1c5187a5fac648c95dafe4ab50d49a7dd1f38aca02ec3e81c2084a34997ea1b6f2a8f196b19835f6e0ac5509b74b8a5b533932190da00f64ede291da0495",
          "sha256": "e9450f9c8da5d968adecd0ec121610e9e321f4933d5c6c46ac32ae55f879455b",
          "sha1": "0c8ed0c35efc989e38b90c49562958b36ed1ed1c",
          "md5": "023162f3b7190513c97676ff41b53d17"
        }
      ]
    }
  ]
}
