{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.300",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.300.jar",
          "url": "qxsl-0.1.300.jar",
          "size": 332782,
          "sha512": "dc599e976553cc95a5dfa88bbcf5f5667870ee6f19715cf1427b1c39deabb54674118ac427a07ee1edb2bc605e329c909f7d38823d944b6dfe8c1ad6265a936c",
          "sha256": "056c8824405d3d2d89ebbb9b8f0a495dcda3824ace33cdf5a7222f176905b0bd",
          "sha1": "0f59665a9e39d9abf8c96c760c37c7b82e30f3c9",
          "md5": "3b6278a815eb29c5b097865ab8fdf17f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.300.jar",
          "url": "qxsl-0.1.300.jar",
          "size": 332782,
          "sha512": "dc599e976553cc95a5dfa88bbcf5f5667870ee6f19715cf1427b1c39deabb54674118ac427a07ee1edb2bc605e329c909f7d38823d944b6dfe8c1ad6265a936c",
          "sha256": "056c8824405d3d2d89ebbb9b8f0a495dcda3824ace33cdf5a7222f176905b0bd",
          "sha1": "0f59665a9e39d9abf8c96c760c37c7b82e30f3c9",
          "md5": "3b6278a815eb29c5b097865ab8fdf17f"
        }
      ]
    }
  ]
}
