{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.304",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.304.jar",
          "url": "qxsl-0.1.304.jar",
          "size": 334128,
          "sha512": "d7bf0e61fdadae98b4ac9b3d9e82500f7c557b64da47791da5eb1dcc365e3044dd234f8c4f0be7ab0d81bc66340f053d20db889e9707cff0521c9d094d696a7f",
          "sha256": "99c8f867cb9f6bef28286ec3bf431a9386305f16cff037bcbf486fabac062076",
          "sha1": "b0750480cfa38c0ae6b4b638e4da14df18b57c6f",
          "md5": "378c0d69cd4b8b64e6ed63aab11d1675"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.304.jar",
          "url": "qxsl-0.1.304.jar",
          "size": 334128,
          "sha512": "d7bf0e61fdadae98b4ac9b3d9e82500f7c557b64da47791da5eb1dcc365e3044dd234f8c4f0be7ab0d81bc66340f053d20db889e9707cff0521c9d094d696a7f",
          "sha256": "99c8f867cb9f6bef28286ec3bf431a9386305f16cff037bcbf486fabac062076",
          "sha1": "b0750480cfa38c0ae6b4b638e4da14df18b57c6f",
          "md5": "378c0d69cd4b8b64e6ed63aab11d1675"
        }
      ]
    }
  ]
}
