{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.304",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.304.jar",
          "url": "qxsl-0.1.304.jar",
          "size": 334138,
          "sha512": "97bce115b53e5af9b8d8b279992797cc9b44958b139386f3738a95bb65c24cd528420991f24859c0b85b8ec37a2784ad027cbd985a879d9ccfac63911cd1c4f6",
          "sha256": "303abc5a732dca7117efac09cf095e402993a91cde628560fcefa141549961dc",
          "sha1": "7633c52cf8a78f0026765545a354814c6ecc9c05",
          "md5": "7fd6e188ec5841b2915d6f2a7921cecb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.304.jar",
          "url": "qxsl-0.1.304.jar",
          "size": 334138,
          "sha512": "97bce115b53e5af9b8d8b279992797cc9b44958b139386f3738a95bb65c24cd528420991f24859c0b85b8ec37a2784ad027cbd985a879d9ccfac63911cd1c4f6",
          "sha256": "303abc5a732dca7117efac09cf095e402993a91cde628560fcefa141549961dc",
          "sha1": "7633c52cf8a78f0026765545a354814c6ecc9c05",
          "md5": "7fd6e188ec5841b2915d6f2a7921cecb"
        }
      ]
    }
  ]
}
