{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.304",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.304.jar",
          "url": "qxsl-0.1.304.jar",
          "size": 333443,
          "sha512": "13d958cf7d7f2fc1f1b6374e5eb6cca69d4339ef4067db880a5bcb535125b93492a6f398d5605eb8450173fcbaf27c1b4153069818de5f4e0d0472a22a1dcd4c",
          "sha256": "9effa8856442ee65e0615975e3c457b817a31c2eaac33ee2808f7ae4d3a2f774",
          "sha1": "ac9ab8c24e83db19c23190fa472ed2ea3217369b",
          "md5": "18e3f600fcabc1b98b8841b698258170"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.304.jar",
          "url": "qxsl-0.1.304.jar",
          "size": 333443,
          "sha512": "13d958cf7d7f2fc1f1b6374e5eb6cca69d4339ef4067db880a5bcb535125b93492a6f398d5605eb8450173fcbaf27c1b4153069818de5f4e0d0472a22a1dcd4c",
          "sha256": "9effa8856442ee65e0615975e3c457b817a31c2eaac33ee2808f7ae4d3a2f774",
          "sha1": "ac9ab8c24e83db19c23190fa472ed2ea3217369b",
          "md5": "18e3f600fcabc1b98b8841b698258170"
        }
      ]
    }
  ]
}
