{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.253",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.253.jar",
          "url": "qxsl-0.1.253.jar",
          "size": 315150,
          "sha512": "746e40468e094af07ed21a04044484f6f2334a97597efe57be9b5833bfe8832eef30779985de851de143099db9ed5e64a2be253b5b134aedbca1ac00c4bda06f",
          "sha256": "24e296c65728d2a7a5760546c7269d9a050278f65f7cf7fbc8aee488914e2282",
          "sha1": "1dc75a37696600343d64fe790c89c8cca2e4f5c3",
          "md5": "d3fddf89c5096fc6b0e2ac10b2310656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.253.jar",
          "url": "qxsl-0.1.253.jar",
          "size": 315150,
          "sha512": "746e40468e094af07ed21a04044484f6f2334a97597efe57be9b5833bfe8832eef30779985de851de143099db9ed5e64a2be253b5b134aedbca1ac00c4bda06f",
          "sha256": "24e296c65728d2a7a5760546c7269d9a050278f65f7cf7fbc8aee488914e2282",
          "sha1": "1dc75a37696600343d64fe790c89c8cca2e4f5c3",
          "md5": "d3fddf89c5096fc6b0e2ac10b2310656"
        }
      ]
    }
  ]
}
