{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.262",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.262.jar",
          "url": "qxsl-0.1.262.jar",
          "size": 323126,
          "sha512": "3ea9938328660d475f70460974dbe975ed03592173fb6f266a9ccdc184132e212650fc3fd375c8d3856ca84f5db32a2f668c3f73ad771c0d967110dda2914bb7",
          "sha256": "5cf8d8369dd90384ba352369348c058f3c0d9b8d6a6f243342f59763c5691b6f",
          "sha1": "7c6f42c196b8b55f9ea3e43d9d91a0bc30d966c5",
          "md5": "b346cc2e2df6d58132224c8c59a7d8dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.262.jar",
          "url": "qxsl-0.1.262.jar",
          "size": 323126,
          "sha512": "3ea9938328660d475f70460974dbe975ed03592173fb6f266a9ccdc184132e212650fc3fd375c8d3856ca84f5db32a2f668c3f73ad771c0d967110dda2914bb7",
          "sha256": "5cf8d8369dd90384ba352369348c058f3c0d9b8d6a6f243342f59763c5691b6f",
          "sha1": "7c6f42c196b8b55f9ea3e43d9d91a0bc30d966c5",
          "md5": "b346cc2e2df6d58132224c8c59a7d8dd"
        }
      ]
    }
  ]
}
