{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.296",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.296.jar",
          "url": "qxsl-0.1.296.jar",
          "size": 328346,
          "sha512": "cd897fcf809eed90f28e58113473ae9edeaaa3e754bf39d560962701522c0939e36657d9dab0e656c3c700ab0ac11155e53a9971bdc79f81a318013fd83c1481",
          "sha256": "3ab7c8d38e183d72d57974489eb9dcc482075f7907a0d9c2fbe897083f404db9",
          "sha1": "cc7b59af74dc0054ce4f8d0d9eb16c09dfc542dc",
          "md5": "e4a2c31ab1826261e96daad3f724ed2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.296.jar",
          "url": "qxsl-0.1.296.jar",
          "size": 328346,
          "sha512": "cd897fcf809eed90f28e58113473ae9edeaaa3e754bf39d560962701522c0939e36657d9dab0e656c3c700ab0ac11155e53a9971bdc79f81a318013fd83c1481",
          "sha256": "3ab7c8d38e183d72d57974489eb9dcc482075f7907a0d9c2fbe897083f404db9",
          "sha1": "cc7b59af74dc0054ce4f8d0d9eb16c09dfc542dc",
          "md5": "e4a2c31ab1826261e96daad3f724ed2c"
        }
      ]
    }
  ]
}
