{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.270",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.270.jar",
          "url": "qxsl-0.1.270.jar",
          "size": 326515,
          "sha512": "6b7c2af9296cf365b706db4319a879252d773f01c4ce461f22331fcc127af2c1b6d18a59dfd170c7a2e957ba0ecfad48c3102619e8f2eae66656bdf32f7faece",
          "sha256": "8752cb77d2b84b02e3ce05d7e21331733b8c973b35470846a4d92fe14cd7b5c4",
          "sha1": "7a98052338082c14303eb8f324c21a36e2419d62",
          "md5": "18a8b46350b432c1dc644c627d89b313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.270.jar",
          "url": "qxsl-0.1.270.jar",
          "size": 326515,
          "sha512": "6b7c2af9296cf365b706db4319a879252d773f01c4ce461f22331fcc127af2c1b6d18a59dfd170c7a2e957ba0ecfad48c3102619e8f2eae66656bdf32f7faece",
          "sha256": "8752cb77d2b84b02e3ce05d7e21331733b8c973b35470846a4d92fe14cd7b5c4",
          "sha1": "7a98052338082c14303eb8f324c21a36e2419d62",
          "md5": "18a8b46350b432c1dc644c627d89b313"
        }
      ]
    }
  ]
}
