{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.268",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.268.jar",
          "url": "qxsl-0.1.268.jar",
          "size": 326243,
          "sha512": "80eeabb4af4fc0c8d0204851233dc19303426214e62a4125a396a1078e04df8ed6cf43ae13c6ec0ab8e1406c74e40ce0af382a6a79b51555ec299a04e9d69cae",
          "sha256": "31995a049d6b8bfb473159a8b1bbf61b78a6ec054aadc672f8d570abd5cbed32",
          "sha1": "d35a3384d68ab252070d28d86fbd912425926098",
          "md5": "33db51bcbbac55c055b860552424bd82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.268.jar",
          "url": "qxsl-0.1.268.jar",
          "size": 326243,
          "sha512": "80eeabb4af4fc0c8d0204851233dc19303426214e62a4125a396a1078e04df8ed6cf43ae13c6ec0ab8e1406c74e40ce0af382a6a79b51555ec299a04e9d69cae",
          "sha256": "31995a049d6b8bfb473159a8b1bbf61b78a6ec054aadc672f8d570abd5cbed32",
          "sha1": "d35a3384d68ab252070d28d86fbd912425926098",
          "md5": "33db51bcbbac55c055b860552424bd82"
        }
      ]
    }
  ]
}
