{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.268",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.268.jar",
          "url": "qxsl-0.1.268.jar",
          "size": 326243,
          "sha512": "f0fcef67f57454c9deeb555c942df42c98ab261efaa315488c92cd5299586e2e3d6052b2021c40ea4daa6ff74cda7060aa1810eff7742c14805f650ae589b1b8",
          "sha256": "edb132a32cec72a0da1b40a19d2d613c634a04de23cabe480408eb80ee3072ef",
          "sha1": "b5b2bfaec2a16c6b32d91d7cf35c5a183f347697",
          "md5": "72da774ceb03195ad3cb9c0b0df2623f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.268.jar",
          "url": "qxsl-0.1.268.jar",
          "size": 326243,
          "sha512": "f0fcef67f57454c9deeb555c942df42c98ab261efaa315488c92cd5299586e2e3d6052b2021c40ea4daa6ff74cda7060aa1810eff7742c14805f650ae589b1b8",
          "sha256": "edb132a32cec72a0da1b40a19d2d613c634a04de23cabe480408eb80ee3072ef",
          "sha1": "b5b2bfaec2a16c6b32d91d7cf35c5a183f347697",
          "md5": "72da774ceb03195ad3cb9c0b0df2623f"
        }
      ]
    }
  ]
}
