{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.277",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.277.jar",
          "url": "qxsl-0.1.277.jar",
          "size": 327117,
          "sha512": "7eaa6a590998ad08a70086349b772ae010c9a7e3b5baf14084ad17e0717cea1c49613ae5f3848daac4d9f22bece66bde11fd7dcc0d5ae151049aeb48ec4c6fda",
          "sha256": "ae93132c668f6aa795f5dd0cb874d6c27a5b3bca802681cdbe2bb8205d29e503",
          "sha1": "17b384b98b520af2632cdfac8ccfb3c741f4030b",
          "md5": "7a2a71295cee57cd0079dac4bce85f69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.277.jar",
          "url": "qxsl-0.1.277.jar",
          "size": 327117,
          "sha512": "7eaa6a590998ad08a70086349b772ae010c9a7e3b5baf14084ad17e0717cea1c49613ae5f3848daac4d9f22bece66bde11fd7dcc0d5ae151049aeb48ec4c6fda",
          "sha256": "ae93132c668f6aa795f5dd0cb874d6c27a5b3bca802681cdbe2bb8205d29e503",
          "sha1": "17b384b98b520af2632cdfac8ccfb3c741f4030b",
          "md5": "7a2a71295cee57cd0079dac4bce85f69"
        }
      ]
    }
  ]
}
