{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.279",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.279.jar",
          "url": "qxsl-0.1.279.jar",
          "size": 327370,
          "sha512": "0d1415eadc17858e8cb307190ab009678e5312b8932c6662de8996f307a0ac378139b3cd18d5155b6a2f0a8b6d16c86a71768af4cad54ac6194d5b14255e213f",
          "sha256": "1acc24d4c128872c3fd6ad4e02f058de25e7be864381eab385ba9578b0d5fa5d",
          "sha1": "a1fbe67a5e443c154c1b01c5f3150e55c5f51160",
          "md5": "3a6fcfaf60e9386887b84b8ff52965ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.279.jar",
          "url": "qxsl-0.1.279.jar",
          "size": 327370,
          "sha512": "0d1415eadc17858e8cb307190ab009678e5312b8932c6662de8996f307a0ac378139b3cd18d5155b6a2f0a8b6d16c86a71768af4cad54ac6194d5b14255e213f",
          "sha256": "1acc24d4c128872c3fd6ad4e02f058de25e7be864381eab385ba9578b0d5fa5d",
          "sha1": "a1fbe67a5e443c154c1b01c5f3150e55c5f51160",
          "md5": "3a6fcfaf60e9386887b84b8ff52965ec"
        }
      ]
    }
  ]
}
