{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.279",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.279.jar",
          "url": "qxsl-0.1.279.jar",
          "size": 327516,
          "sha512": "bf789e73846de2b194708c746ffd3a74d76bbc89ff330803491c93edd7a787720a021bf3f7f29600ee9fd816c2c37c5f9889e4c364c147f9e98f9d6f3d5d1212",
          "sha256": "79ad4d4a5bd7097882c971fc2b1a2c971c59c40272458967721eadf9ad2bdb12",
          "sha1": "181da49c2fe50a7b3bfc8f68dab98d047457c62c",
          "md5": "08baefa7161b01f56862feb5fc501fbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.279.jar",
          "url": "qxsl-0.1.279.jar",
          "size": 327516,
          "sha512": "bf789e73846de2b194708c746ffd3a74d76bbc89ff330803491c93edd7a787720a021bf3f7f29600ee9fd816c2c37c5f9889e4c364c147f9e98f9d6f3d5d1212",
          "sha256": "79ad4d4a5bd7097882c971fc2b1a2c971c59c40272458967721eadf9ad2bdb12",
          "sha1": "181da49c2fe50a7b3bfc8f68dab98d047457c62c",
          "md5": "08baefa7161b01f56862feb5fc501fbe"
        }
      ]
    }
  ]
}
