{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.279",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.279.jar",
          "url": "qxsl-0.1.279.jar",
          "size": 327516,
          "sha512": "485abc6c172ee2bb2b8fd786599299e16d3c2447e72445c477ac47f16e97db97827d07f75da2b5c7f634c47880ff42eaca5a98e9f5160858b9df3b884377ca67",
          "sha256": "f6e8b07e6326224154e2c5dd3d7df03cbb11083504c191e583388ab0f039d681",
          "sha1": "6ad73a5b788e0ebcb8e377c1cfeac457d3f015e6",
          "md5": "35b0f15520b6a26ced9b4560137a96ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.279.jar",
          "url": "qxsl-0.1.279.jar",
          "size": 327516,
          "sha512": "485abc6c172ee2bb2b8fd786599299e16d3c2447e72445c477ac47f16e97db97827d07f75da2b5c7f634c47880ff42eaca5a98e9f5160858b9df3b884377ca67",
          "sha256": "f6e8b07e6326224154e2c5dd3d7df03cbb11083504c191e583388ab0f039d681",
          "sha1": "6ad73a5b788e0ebcb8e377c1cfeac457d3f015e6",
          "md5": "35b0f15520b6a26ced9b4560137a96ee"
        }
      ]
    }
  ]
}
