{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.294",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.294.jar",
          "url": "qxsl-0.1.294.jar",
          "size": 328617,
          "sha512": "cd6efc9133a789ce5173166e3f78d62a5ad3c1a46fd3da27b6809764fe56be8ea1a977f64195818747999967eb8e20a531c5fd4dc1f0987c35a37c80413d9aa8",
          "sha256": "86acafa33dd2279f9f12117967a761194e5a254bbdc76745a84be563288c5162",
          "sha1": "a040e0cebda71af622c9eb4dc8d12b1a0908138e",
          "md5": "33ff94be59f104f3c09c78aa416959cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.294.jar",
          "url": "qxsl-0.1.294.jar",
          "size": 328617,
          "sha512": "cd6efc9133a789ce5173166e3f78d62a5ad3c1a46fd3da27b6809764fe56be8ea1a977f64195818747999967eb8e20a531c5fd4dc1f0987c35a37c80413d9aa8",
          "sha256": "86acafa33dd2279f9f12117967a761194e5a254bbdc76745a84be563288c5162",
          "sha1": "a040e0cebda71af622c9eb4dc8d12b1a0908138e",
          "md5": "33ff94be59f104f3c09c78aa416959cc"
        }
      ]
    }
  ]
}
