{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.294",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.294.jar",
          "url": "qxsl-0.1.294.jar",
          "size": 328914,
          "sha512": "abc4c63b6da028e62f5ee3b10857f03ce67c946ae7ac7f36344ac1409e0231e20cf65054fe4633e5404e18e0d607a724a567ad80812b21b6c6404dec1568ded3",
          "sha256": "60dd12ced872f882d8a6fe2ae61e84d3d95ade6fee4c99598e18e02589f60d54",
          "sha1": "1a1c7b22f06132367fd983ab49b56cecbc69bba2",
          "md5": "59c6798a8cfcd527fe07c820ecdd9a7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.294.jar",
          "url": "qxsl-0.1.294.jar",
          "size": 328914,
          "sha512": "abc4c63b6da028e62f5ee3b10857f03ce67c946ae7ac7f36344ac1409e0231e20cf65054fe4633e5404e18e0d607a724a567ad80812b21b6c6404dec1568ded3",
          "sha256": "60dd12ced872f882d8a6fe2ae61e84d3d95ade6fee4c99598e18e02589f60d54",
          "sha1": "1a1c7b22f06132367fd983ab49b56cecbc69bba2",
          "md5": "59c6798a8cfcd527fe07c820ecdd9a7e"
        }
      ]
    }
  ]
}
