{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.305.jar",
          "url": "qxsl-0.1.305.jar",
          "size": 336445,
          "sha512": "1d95a4b410382ccfe5b1b10646e649661c1566002a8c001aa4a4430825513f520435228cf6155e4a342fb75c7b369c5bc0af8153a0ff56a7c735a2ced683bb51",
          "sha256": "c04a114a12841b0ec20a28565bdd7ee89c3f71299a3526afb18f0cf1e61e2839",
          "sha1": "7011b520447d63859dfdfe76ffa8e5c3c5cc2ecf",
          "md5": "ac6f6dbd6b88de3d4cff0d4aaa41fa95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.305.jar",
          "url": "qxsl-0.1.305.jar",
          "size": 336445,
          "sha512": "1d95a4b410382ccfe5b1b10646e649661c1566002a8c001aa4a4430825513f520435228cf6155e4a342fb75c7b369c5bc0af8153a0ff56a7c735a2ced683bb51",
          "sha256": "c04a114a12841b0ec20a28565bdd7ee89c3f71299a3526afb18f0cf1e61e2839",
          "sha1": "7011b520447d63859dfdfe76ffa8e5c3c5cc2ecf",
          "md5": "ac6f6dbd6b88de3d4cff0d4aaa41fa95"
        }
      ]
    }
  ]
}
