{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.282",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.282.jar",
          "url": "qxsl-0.1.282.jar",
          "size": 327684,
          "sha512": "035e91543e14c67b4acba14c51c97bbb0c16cb6cc3e68c2318e8d8b8352ef79a52f346ff65a1a1f02f4eb5b7f3fbdaff11418e0454d4b063dfb6f1dc8c89e98c",
          "sha256": "deba9b05dbc7597184f5e5443ddd81a6b06409a1f8cd10a9b4c47518aac5fb98",
          "sha1": "c10edf5564351bc33a2eb83943440508fd614eae",
          "md5": "2632b99def10168a4ea97523e1eb457d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.282.jar",
          "url": "qxsl-0.1.282.jar",
          "size": 327684,
          "sha512": "035e91543e14c67b4acba14c51c97bbb0c16cb6cc3e68c2318e8d8b8352ef79a52f346ff65a1a1f02f4eb5b7f3fbdaff11418e0454d4b063dfb6f1dc8c89e98c",
          "sha256": "deba9b05dbc7597184f5e5443ddd81a6b06409a1f8cd10a9b4c47518aac5fb98",
          "sha1": "c10edf5564351bc33a2eb83943440508fd614eae",
          "md5": "2632b99def10168a4ea97523e1eb457d"
        }
      ]
    }
  ]
}
