{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.282",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.282.jar",
          "url": "qxsl-0.1.282.jar",
          "size": 327684,
          "sha512": "b046a8c57029b1ac44ae8f95594532d3585bf837c7223a5ccb9bac94900304df65e348dbaf6dd7f281df01f09890ed461dcd960e0a8758eab449f5c2af56c479",
          "sha256": "0bf4b109908b059740a7dfa94dfe7c88c680b0ef062498568732d00a39b41e2f",
          "sha1": "dc0a5f723ad935151d051bf5dfff9de64bab2bb4",
          "md5": "ed4e0b25e80d68f62c2005526533bfdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.282.jar",
          "url": "qxsl-0.1.282.jar",
          "size": 327684,
          "sha512": "b046a8c57029b1ac44ae8f95594532d3585bf837c7223a5ccb9bac94900304df65e348dbaf6dd7f281df01f09890ed461dcd960e0a8758eab449f5c2af56c479",
          "sha256": "0bf4b109908b059740a7dfa94dfe7c88c680b0ef062498568732d00a39b41e2f",
          "sha1": "dc0a5f723ad935151d051bf5dfff9de64bab2bb4",
          "md5": "ed4e0b25e80d68f62c2005526533bfdb"
        }
      ]
    }
  ]
}
