{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.289",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.289.jar",
          "url": "qxsl-0.1.289.jar",
          "size": 324913,
          "sha512": "95d7cf0de00621bf6ca13b18d2d199daf018ac3e3de825eb940380cc777e37999c56495a24dd6425eb2539c69312276b7a0c94b57dbab37ad88d546e02f09424",
          "sha256": "b8f15e46449561f303e33242cdf70211f07e4ee92bf1669d571edd8743266fc4",
          "sha1": "5761f2d1a948b6defde5e1bb011b8ea401b59884",
          "md5": "811f624721471b939c74ff44de3b600e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.289.jar",
          "url": "qxsl-0.1.289.jar",
          "size": 324913,
          "sha512": "95d7cf0de00621bf6ca13b18d2d199daf018ac3e3de825eb940380cc777e37999c56495a24dd6425eb2539c69312276b7a0c94b57dbab37ad88d546e02f09424",
          "sha256": "b8f15e46449561f303e33242cdf70211f07e4ee92bf1669d571edd8743266fc4",
          "sha1": "5761f2d1a948b6defde5e1bb011b8ea401b59884",
          "md5": "811f624721471b939c74ff44de3b600e"
        }
      ]
    }
  ]
}
