{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.289",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.289.jar",
          "url": "qxsl-0.1.289.jar",
          "size": 324913,
          "sha512": "dbf792a67cbb3c2567748dd64aa5a73cc756896776b0fd7a32dd2e1860e3a4568fc439b66e17162df32019c6138ac87af19fb8b28c0f94215986e669da9d9bee",
          "sha256": "7aa8f11340c24be601e0c9ea47fb752b38dbaa8106731e078b722eb7973a1ac9",
          "sha1": "3ed39fe676919220fc773f6bc6a193426074171a",
          "md5": "ded776a4ea8d4a2c861ee3f4ff7b0d29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.289.jar",
          "url": "qxsl-0.1.289.jar",
          "size": 324913,
          "sha512": "dbf792a67cbb3c2567748dd64aa5a73cc756896776b0fd7a32dd2e1860e3a4568fc439b66e17162df32019c6138ac87af19fb8b28c0f94215986e669da9d9bee",
          "sha256": "7aa8f11340c24be601e0c9ea47fb752b38dbaa8106731e078b722eb7973a1ac9",
          "sha1": "3ed39fe676919220fc773f6bc6a193426074171a",
          "md5": "ded776a4ea8d4a2c861ee3f4ff7b0d29"
        }
      ]
    }
  ]
}
