{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.289",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.289.jar",
          "url": "qxsl-0.1.289.jar",
          "size": 324913,
          "sha512": "11aefc655732f7c051409b4bbcfeda4f937d21e1c1edbd7e50c3770e0075dbc36cf0bc118a207c5496b99651ef4242cebc7a5444dc928d031edf45eb522d2d9b",
          "sha256": "dd74550c0b81450e9192758e8a5cc6e6710f1c49ec2ac5e143e21701c167b925",
          "sha1": "621f5c8c7fabf27703a0af87a24945b9bc657b3f",
          "md5": "25a0cfdc1386cf3b234965c3aa50856c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.289.jar",
          "url": "qxsl-0.1.289.jar",
          "size": 324913,
          "sha512": "11aefc655732f7c051409b4bbcfeda4f937d21e1c1edbd7e50c3770e0075dbc36cf0bc118a207c5496b99651ef4242cebc7a5444dc928d031edf45eb522d2d9b",
          "sha256": "dd74550c0b81450e9192758e8a5cc6e6710f1c49ec2ac5e143e21701c167b925",
          "sha1": "621f5c8c7fabf27703a0af87a24945b9bc657b3f",
          "md5": "25a0cfdc1386cf3b234965c3aa50856c"
        }
      ]
    }
  ]
}
