{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.283",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.283.jar",
          "url": "qxsl-0.1.283.jar",
          "size": 327684,
          "sha512": "2c8bae10f73a3f7496bf86f10d2c127ef99a8edb737d949f85713531e33024a14d2781008c6cda4b5c606ce094b20d67233f8c4330a891a232923d59b8035e27",
          "sha256": "37803e15ec17e8e69284475ac81ede4b4473066256df82703f51fc0878fed35f",
          "sha1": "378683664168a256d9dbc965af8ce24935c38672",
          "md5": "b933cfa7b2a6c8d673f0c0ab5ee95347"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.283.jar",
          "url": "qxsl-0.1.283.jar",
          "size": 327684,
          "sha512": "2c8bae10f73a3f7496bf86f10d2c127ef99a8edb737d949f85713531e33024a14d2781008c6cda4b5c606ce094b20d67233f8c4330a891a232923d59b8035e27",
          "sha256": "37803e15ec17e8e69284475ac81ede4b4473066256df82703f51fc0878fed35f",
          "sha1": "378683664168a256d9dbc965af8ce24935c38672",
          "md5": "b933cfa7b2a6c8d673f0c0ab5ee95347"
        }
      ]
    }
  ]
}
