{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.283",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.283.jar",
          "url": "qxsl-0.1.283.jar",
          "size": 327684,
          "sha512": "1303b37959364b600613f3a0ace2a420df84f54a0fa75eab07210234060ebad5066798a6063431a64c09fbc15172ec07823d748741fd99069b911c8d40a19ba2",
          "sha256": "4df4e5d87b38dba0f0cb4d3753f7a7658d1cf1559b2fd8e7510fe2c1907c08c9",
          "sha1": "95fe0ccb9a8b844c41ec6d909c6790a81a7fab22",
          "md5": "75eef0d19e6cc54333f91eed5fde0bb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.283.jar",
          "url": "qxsl-0.1.283.jar",
          "size": 327684,
          "sha512": "1303b37959364b600613f3a0ace2a420df84f54a0fa75eab07210234060ebad5066798a6063431a64c09fbc15172ec07823d748741fd99069b911c8d40a19ba2",
          "sha256": "4df4e5d87b38dba0f0cb4d3753f7a7658d1cf1559b2fd8e7510fe2c1907c08c9",
          "sha1": "95fe0ccb9a8b844c41ec6d909c6790a81a7fab22",
          "md5": "75eef0d19e6cc54333f91eed5fde0bb2"
        }
      ]
    }
  ]
}
