{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.286",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.286.jar",
          "url": "qxsl-0.1.286.jar",
          "size": 325618,
          "sha512": "2c1e2d299dfe2cedd8e9bdc4a0a2c131f193e480848fa9e17f176cd0ce688be8aeaf1f8c3fb4819d699937ed843ca347d916c34a0fd3563a39a9e11850917108",
          "sha256": "697c9f5f1c90a41d20061c4b3305698a26ee506637cf26416bdab169314d10ed",
          "sha1": "a2ce227c5c2f7800b4ba0d807baddc048a4f7d93",
          "md5": "8220db7080f6eb0586fd2ed77d96f40b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.286.jar",
          "url": "qxsl-0.1.286.jar",
          "size": 325618,
          "sha512": "2c1e2d299dfe2cedd8e9bdc4a0a2c131f193e480848fa9e17f176cd0ce688be8aeaf1f8c3fb4819d699937ed843ca347d916c34a0fd3563a39a9e11850917108",
          "sha256": "697c9f5f1c90a41d20061c4b3305698a26ee506637cf26416bdab169314d10ed",
          "sha1": "a2ce227c5c2f7800b4ba0d807baddc048a4f7d93",
          "md5": "8220db7080f6eb0586fd2ed77d96f40b"
        }
      ]
    }
  ]
}
