{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.274",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.274.jar",
          "url": "qxsl-0.1.274.jar",
          "size": 327433,
          "sha512": "73899531590955ceed7e1b0d4f429aa75f6da18259481dd9d9c8459e175c1656ce574ecb545e21c4393a9ab317984d072aa660f33859d2db5d85a4b303616e3f",
          "sha256": "c55d91bb65973b25289d1e4652e99ce923c393374e163662f8dec5a7c8aea869",
          "sha1": "89c9c02b694a7c248ff54f9c57ca87443c11e60b",
          "md5": "e725b3904e35030b1cd754796f14d728"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.274.jar",
          "url": "qxsl-0.1.274.jar",
          "size": 327433,
          "sha512": "73899531590955ceed7e1b0d4f429aa75f6da18259481dd9d9c8459e175c1656ce574ecb545e21c4393a9ab317984d072aa660f33859d2db5d85a4b303616e3f",
          "sha256": "c55d91bb65973b25289d1e4652e99ce923c393374e163662f8dec5a7c8aea869",
          "sha1": "89c9c02b694a7c248ff54f9c57ca87443c11e60b",
          "md5": "e725b3904e35030b1cd754796f14d728"
        }
      ]
    }
  ]
}
