{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.274",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.274.jar",
          "url": "qxsl-0.1.274.jar",
          "size": 327433,
          "sha512": "723d32cce8a0c8536879bfc10d1e810954b7ef8c8a9aaa0555da1cca8e76f590328079cfde4b1d5c1efe33af01d051ac23c42923b4197cbda7c7f146bcad75a5",
          "sha256": "e986666251319a6da26e5855b911a9c58bcc799c3724466d47c55afff4cb7b4e",
          "sha1": "9c5d213b75d21b9cbde3c24d169873e88a9a1621",
          "md5": "e851b58a6e6c837cc17aaef8400795e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.274.jar",
          "url": "qxsl-0.1.274.jar",
          "size": 327433,
          "sha512": "723d32cce8a0c8536879bfc10d1e810954b7ef8c8a9aaa0555da1cca8e76f590328079cfde4b1d5c1efe33af01d051ac23c42923b4197cbda7c7f146bcad75a5",
          "sha256": "e986666251319a6da26e5855b911a9c58bcc799c3724466d47c55afff4cb7b4e",
          "sha1": "9c5d213b75d21b9cbde3c24d169873e88a9a1621",
          "md5": "e851b58a6e6c837cc17aaef8400795e8"
        }
      ]
    }
  ]
}
