{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.280",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.280.jar",
          "url": "qxsl-0.1.280.jar",
          "size": 327516,
          "sha512": "bf526926ad2f5a0ac62833c380297b7300498393a45bc874d2c802535d411ff9b97b13e2ccb220af5eb71462741bad3b2ad5cc2c6e8aadad49141e2e2fcfb131",
          "sha256": "3916d6e7e8861c7a87a01caefae2607a4e344432b13573881dabaf13e0d56924",
          "sha1": "8f247e0eb4e2073621146d860e25396e1c1a61f2",
          "md5": "cb8028724dbea3efec3337e924f9c3fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.280.jar",
          "url": "qxsl-0.1.280.jar",
          "size": 327516,
          "sha512": "bf526926ad2f5a0ac62833c380297b7300498393a45bc874d2c802535d411ff9b97b13e2ccb220af5eb71462741bad3b2ad5cc2c6e8aadad49141e2e2fcfb131",
          "sha256": "3916d6e7e8861c7a87a01caefae2607a4e344432b13573881dabaf13e0d56924",
          "sha1": "8f247e0eb4e2073621146d860e25396e1c1a61f2",
          "md5": "cb8028724dbea3efec3337e924f9c3fe"
        }
      ]
    }
  ]
}
