{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.280",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.280.jar",
          "url": "qxsl-0.1.280.jar",
          "size": 327562,
          "sha512": "9c57aea5ae7e39ddb6b662d7f4363a979693268c11822cb451c0f1ea797d7e76d85d9c6fa7af198a2a521ffb55dec536625399300d536b626147cdd8add442b4",
          "sha256": "ca07383c70bda0dfb17fb584f7ef1251d54db8c3962aa9a23c3ca765a8db8f90",
          "sha1": "f5feca19b1e2ed7bd4882907714fccdb0df988b7",
          "md5": "620f534f03bafdf154a674d5476942ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.280.jar",
          "url": "qxsl-0.1.280.jar",
          "size": 327562,
          "sha512": "9c57aea5ae7e39ddb6b662d7f4363a979693268c11822cb451c0f1ea797d7e76d85d9c6fa7af198a2a521ffb55dec536625399300d536b626147cdd8add442b4",
          "sha256": "ca07383c70bda0dfb17fb584f7ef1251d54db8c3962aa9a23c3ca765a8db8f90",
          "sha1": "f5feca19b1e2ed7bd4882907714fccdb0df988b7",
          "md5": "620f534f03bafdf154a674d5476942ba"
        }
      ]
    }
  ]
}
