{
  "formatVersion": "1.1",
  "component": {
    "group": "qxsl",
    "module": "qxsl",
    "version": "0.1.280",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qxsl-0.1.280.jar",
          "url": "qxsl-0.1.280.jar",
          "size": 327562,
          "sha512": "e3fac6e964084c666c37b9baa901c34125ad2bb9fb3889b28089927b257f73d3f7ebc6390e5e17cc65c81cb556ef54c886fbbe44e9cf89f26f0bb1eed6297168",
          "sha256": "ef69865837ca373c07789752eab110ba143500de37024ed2bdf1b0406daed028",
          "sha1": "28b6208bb5b8079534fc3c26bd4b8c420899a2e2",
          "md5": "ba20dcf116da2816f9d902bfb2fd682f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qxsl-0.1.280.jar",
          "url": "qxsl-0.1.280.jar",
          "size": 327562,
          "sha512": "e3fac6e964084c666c37b9baa901c34125ad2bb9fb3889b28089927b257f73d3f7ebc6390e5e17cc65c81cb556ef54c886fbbe44e9cf89f26f0bb1eed6297168",
          "sha256": "ef69865837ca373c07789752eab110ba143500de37024ed2bdf1b0406daed028",
          "sha1": "28b6208bb5b8079534fc3c26bd4b8c420899a2e2",
          "md5": "ba20dcf116da2816f9d902bfb2fd682f"
        }
      ]
    }
  ]
}
